Select a.date, a.close as aapl_close,
(Select m.close from stocks.stock_data_msft m where m.date=a.date) as msft_close,
(Select g.close from stocks.stock_data_googl g where g.date=a.date) as googl_close,
(Select c.close from stocks.stock_data_cmcsa c where c.date=a.date) as cmcsa_close,
(Select d.close from stocks.etf_data_dia d where d.date=a.date) as dia_close,
(Select i.close from stocks.etf_data_ivv i where i.date=a.date) as ivv_close,
(Select w.close from stocks.etf_data_iwm w where w.date=a.date) as iwm_close,
(Select q.close from stocks.etf_data_qqq q where q.date=a.date) as qqq_close,
 a.volume as aapl_volume,
(Select m.volume from stocks.stock_data_msft m where m.date=a.date) as msft_volume,
(Select g.volume from stocks.stock_data_googl g where g.date=a.date) as googl_volume,
(Select c.volume from stocks.stock_data_cmcsa c where c.date=a.date) as cmcsa_volume,
(Select d.volume from stocks.etf_data_dia d where d.date=a.date) as dia_volume,
(Select i.volume from stocks.etf_data_ivv i where i.date=a.date) as ivv_volume,
(Select w.volume from stocks.etf_data_iwm w where w.date=a.date) as iwm_volume,
(Select q.volume from stocks.etf_data_qqq q where q.date=a.date) as qqq_volume,
 a.daily_return as aapl_daily_return,
(Select m.daily_return from stocks.stock_data_msft m where m.date=a.date) as msft_daily_return,
(Select g.daily_return from stocks.stock_data_googl g where g.date=a.date) as googl_daily_return,
(Select c.daily_return from stocks.stock_data_cmcsa c where c.date=a.date) as cmcsa_daily_return,
(Select d.daily_return from stocks.etf_data_dia d where d.date=a.date) as dia_daily_return,
(Select i.daily_return from stocks.etf_data_ivv i where i.date=a.date) as ivv_daily_return,
(Select w.daily_return from stocks.etf_data_iwm w where w.date=a.date) as iwm_daily_return,
(Select q.daily_return from stocks.etf_data_qqq q where q.date=a.date) as qqq_daily_return,
 a.seven_day_ma as aapl_7day_ma,
(Select m.seven_day_ma from stocks.stock_data_msft m where m.date=a.date) as msft_seven_day_ma,
(Select g.seven_day_ma from stocks.stock_data_googl g where g.date=a.date) as googl_seven_day_ma,
(Select c.seven_day_ma from stocks.stock_data_cmcsa c where c.date=a.date) as cmcsa_seven_day_ma,
(Select d.seven_day_ma from stocks.etf_data_dia d where d.date=a.date) as dia_seven_day_ma,
(Select i.seven_day_ma from stocks.etf_data_ivv i where i.date=a.date) as ivv_seven_day_ma,
(Select w.seven_day_ma from stocks.etf_data_iwm w where w.date=a.date) as iwm_seven_day_ma,
(Select q.seven_day_ma from stocks.etf_data_qqq q where q.date=a.date) as qqq_seven_day_ma,
 a.thirty_day_ma as aapl_30day_ma,
(Select m.thirty_day_ma from stocks.stock_data_msft m where m.date=a.date) as msft_thirty_day_ma,
(Select g.thirty_day_ma from stocks.stock_data_googl g where g.date=a.date) as googl_thirty_day_ma,
(Select c.thirty_day_ma from stocks.stock_data_cmcsa c where c.date=a.date) as cmcsa_thirty_day_ma,
(Select d.thirty_day_ma from stocks.etf_data_dia d where d.date=a.date) as dia_thirty_day_ma,
(Select i.thirty_day_ma from stocks.etf_data_ivv i where i.date=a.date) as ivv_thirty_day_ma,
(Select w.thirty_day_ma from stocks.etf_data_iwm w where w.date=a.date) as iwm_thirty_day_ma,
(Select q.thirty_day_ma from stocks.etf_data_qqq q where q.date=a.date) as qqq_thirty_day_ma,
a.volatility as aapl_volatility,
(Select m.volatility from stocks.stock_data_msft m where m.date=a.date) as msft_volatility,
(Select g.volatility from stocks.stock_data_googl g where g.date=a.date) as googl_volatility,
(Select c.volatility from stocks.stock_data_cmcsa c where c.date=a.date) as cmcsa_volatility,
(Select d.volatility from stocks.etf_data_dia d where d.date=a.date) as dia_volatility,
(Select i.volatility from stocks.etf_data_ivv i where i.date=a.date) as ivv_volatility,
(Select w.volatility from stocks.etf_data_iwm w where w.date=a.date) as iwm_volatility,
(Select q.volatility from stocks.etf_data_qqq q where q.date=a.date) as qqq_volatility
 from stocks.stock_data_aapl a
 WHERE date BETWEEN '2022-01-01' AND '2024-10-31';
